name: Backend Tests
on: [push]
jobs:
  Backend-Tests:
    runs-on: ubuntu-latest
    services:
        mongodb:
            image: mongo
            options: >-
              --health-cmd mongo
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        working-directory: ./backend/
        run: npm install
      - name: Start MongoDB
        run: sudo systemctl start mongod
      - name: Run Adventure component tests
        working-directory: ./backend/
        run: npm test AdventureStore.test.js FilterService.test.js
      - name: Run Request component tests
        working-directory: ./backend/
        run: npm test RequestStore.test.js
      - name: Run Account integration tests
        working-directory: ./backend/
        run: npm test Account.test.js
      - name: Run Adventure integration tests
        working-directory: ./backend/
        run: npm test Adventure.test.js
      - name: Run Chat integration tests
        working-directory: ./backend/
        run: npm test Chat.test.js
      - name: Run Profile integration tests
        working-directory: ./backend/
        run: npm test Profile.test.js
      - name: Run Request integration tests
        working-directory: ./backend/
        run: npm test Request.test.js
      - name: Run all integration tests
        working-directory: ./backend/
        run: npm test integration